### PR TITLE
73: Minor java-doc improvements

### PR DESCRIPTION
**Pull request by andi-huber**
clarify the meaning of 'inverse'
clarify 'root'

---
This change is [Reviewable](https://reviewable.io/reviews/unitsofmeasurement/unit-api/74)

### CODE REVIEW

**Comment by keilw** [comment]
@andi-huber Thanks, I appreciate to see others from Austria/Vienna (JSR 382 Co Spec Lead @struberg is also based there) but in relevant repositories like API, RI (Indriya) or the TCK we need to have the proposing  developer join the JCP as Associate Member: https://jcp.org/en/participation/membership. Would you be willing to join? (either as associate member or if you consider joining as Full EG member and your type of employment allows it, also Full member or Corporate rep)

**Comment by andi-huber** [comment]
Thanks Werner!
I've no JCP membership yet. Without knowing any details (thanks for the links you provided) I might consider joining as an individual.

**Comment by keilw** [comment]
Great, please let us know, if you need any help (all 3 Spec Leads were also in the JCP EC at some point) Individual members can either be Associate (which is the easiest, fastest option) or Full Members (which requires to sign a larger agreement called JSPA) chose whichever you are more comfortable with.

**Comment by andi-huber** [comment]
I've signed a JCP Associate Membership Agreement on 27th of March. Still I'm not listed as JCP member. Hope it will not take too long.
Cheers!

**Comment by keilw** [comment]
Thanks, as only 2 files are affected, would it be OK to create the PR again from a fresh codebase?

**Comment by keilw** [comment]
And if you haven't done so, could you also please nominate yourself to join as Contributor: https://jcp.org/en/jsr/egnom?id=385

**Comment by andi-huber** [comment]
Thanks again! I've now nominated myself as Contributor.

**Comment by andi-huber** [comment]
I've merged changes from origin into my fork, such that PR has no more conflicts.

**Comment by keilw** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unitsofmeasurement/unit-api/74)*

**Comment by keilw** [comment]
@andi-huber Welcome as Committer to JSR 385, https://jcp.org/en/jsr/detail?id=385 was recently updated so I merged the PR, as manual intervention and conflict-resolution was necessary in case of `Quantity`, please check out the result if everything was merged correctly.

**Comment by andi-huber** [comment]
Everything was merged correctly, thanks!

**Pull request merged**
