### PR TITLE
Replace tabulations by spaces. No code change in this commit.

### PR DESCRIPTION
**Pull request by desruisseaux**
The code currently contains a mix of use of spaces or use of tabulations. Some indentations are 2 characters and other are 4 characters. In order to uniformize, this commits replace tabulation by 4 spaces in order.

This commit does not address yet the mismatches between 2 and 4 spaces indentations. Which indentation to use is a separated question.

---
This change is [Reviewable](https://reviewable.io/reviews/unitsofmeasurement/unit-api/120)

### CODE REVIEW

**Comment by keilw** [comment]
Is this a correct PR now? For IDE or repository if we merge it, there should also be certain settings like .editorinfo or whatever to keep it that way ;-)

**Comment by desruisseaux** [comment]
The merge is ready. But it does not resolve the question of which indentation to choose (2 or 4 spaces). Right now, some classes use 2 spaces and other 4 spaces. IDE may be configured after this choice is made. The most common value as far as I know is 4 spaces.

**Comment by keilw** [comment]
I mostly use Eclipse-based IDEs and there is a config for that here: https://github.com/unitsofmeasurement/unit-api/tree/master/src/main/config
It is also used by certain Maven plugins, at least when particular profiles or goals are called explicitly, not for every build.

**Comment by desruisseaux** [comment]
Yes I noticed this config. But it does not tell us what JSR-385 chooses for indentation size. The `eclipse-formatter-config.xml` specifies 2 spaces, but this is not the most usual value for Java sources. The question is whether the group wants to applies this 2 space indentations to all source files, or edit the `eclipse-formatter-config.xml` file for setting 4 spaces.

**Comment by keilw** [comment]
Maybe ask it on the mailing list, only a few people might notice that issue or PR, and I doubt everyone uses Eclipse, so while setting it to the desired value there, others may have to adjust their preferred IDE.

**Comment by desruisseaux** [comment]
I use NetBeans. But I don't think that this issue affects any user of any IDE. It is about configuration of a Unit-API project only; developers don't have to change their habits for their projects.

**Comment by keilw** [comment]
I think we need something like this file: https://github.com/JavaMoney/xs2a/blob/develop/.editorconfig
I contribute to that project alongside many other contributors likely in several different IDEs (most of them seem to use IntelliJ, I use Eclipse/Red Hat Studio) and it seems to work.

**Comment by desruisseaux** [comment]
I'm not familiar with this configuration file. Actually while I do not object against auto-formatting for small projects like Unit-API, I never use any of them on my side (I think they improve readability only if the code was badly formatted in the first place; otherwise they actually decrease readability). I'm neutral on the formatting convention selected for Unit-API and leave configuration to others. I just point out that:

* Unit-API currently uses a mix of at least 2 different conventions.
* A majority of Unit-API seems to use 2 spaces indentation.
* The most usual convention is 4 spaces as far as I know.

I leave the decision to you or other on what you want to do.

**Comment by keilw** [comment]
This kind of file is not uncommon, I know it was proposed and contributed to a few other projects. The xs2a project also uses 4 spaces. So why not go for that. If we had 2 it could be something from a heritage, there have been several precursors all the way back to JSR 275 ;-)

**Pull request merged**
