### PR TITLE
Fix apparent typo in JavaDoc of Quantity

### PR DESCRIPTION
**Pull request by vorburger**
@keilw

- - -
This change is [Reviewable](https://reviewable.io/reviews/unitsofmeasurement/unit-api/254)

### CODE REVIEW

**Review by keilw — CHANGES_REQUESTED** [review]
@vorburger Kelvin is wrong here. 
The numeric value is indeed a little incorrect, 
It should be `2°C + 1°C = 276.15°C`.

If you could fix that I'd be happy to merge the PR.

**Comment by vorburger** [comment]
> should be `2°C + 1°C = 276.15°C`

Wait, what? Is that a typo, or intentional? It doesn't make sense to me, like this... adding two quantities (2+1) of the same °C unit, becomes a 276.15°C, really?

**Comment by keilw** [comment]
Yes, that's the whole point of Quantity.Scale.

Check out the Indriya (RI) [TemperatureTest](https://github.com/unitsofmeasurement/indriya/blob/master/src/test/java/tech/units/indriya/quantity/TemperatureTest.java)
or
[QuantitiesTest](https://github.com/unitsofmeasurement/seshat/blob/master/src/test/java/tech/uom/seshat/QuantitiesTest.java) by Seshat, another compatible implementation.

As well as TemperatureDemo for 

- [Indriya](https://github.com/unitsofmeasurement/uom-demos/blob/master/console/basic/src/main/java/tech/uom/demo/basic/quantity/TemperatureDemo.java)
- [Seshat](https://github.com/unitsofmeasurement/uom-demos/blob/master/console/impl/seshat/src/main/java/tech/uom/demo/impl/seshat/TemperatureDemo.java)

Ask @desruisseaux for the motivation.

**Comment by desruisseaux** [comment]
Hello @vorburger

> adding two quantities (2+1) of the same °C unit, becomes a 276.15°C, really?

Yes, really at least in some cases for the particular case of °C. Actually it depends on whether 1°C is an absolute temperature or an increment. This is why there is a `Quantity.Scale` enumeration with two values: `ABSOLUTE` and `RELATIVE`.

If 1°C is an *increment* (`Scale.RELATIVE`), then 2°C + 1°C is equal to 3°C. But if 1°C is a temperature measurement (`Scale.ABSOLUTE`), then the calculation must be done in K. This is required by thermodynamic laws. So 2°C + 1°C is equal to 275.15 K + 274.15 K = 549.30 K = 276.15°C. The reason is that we are computing the amount of energy in a system.

So if you want 2°C + 1°C = 3°C, you need to tell the library that 1°C is an increment rather than an absolute measurement. This ambiguity exists for °C and not for other standard units (ignoring °F) because °C has a zero which is shifted compared to the base SI unit. For non-shifted units, the distinction between absolute and relative makes no difference, because the shift is zero.

**Comment by keilw** [comment]
@vorburger Any chance you could fix this PR? As it's just a single digit, we could also close it and address the viable part of it separately.

**Pull request closed without merging**
