### PR TITLE
Added 'Contribute' section to README

### PR DESCRIPTION
**Pull request by thodorisbais**
Hello,

I've accidentally noticed that indriya's README has a reference to its relative contribution wiki, so, I thought about introducing it here, too.

This PR is left as a WIP, though, because I believe there is still some consultation needed regarding the changes that need to happen on this project's wiki.

Cheers,
TB

---
This change is [Reviewable](https://reviewable.io/reviews/unitsofmeasurement/unit-api/135)

### CODE REVIEW

**Comment by Daniel-Dos** [comment]
Hi

from what I noticed, it seems to me that it will not change much. I believe it is exactly like that of indriya.

**Comment by thodorisbais** [comment]
@Daniel-Dos I think we need to improve it a bit; at least, there is a mismatch in the intention of the links:

screenshot 2018-10-28 at 18 57 42

I would be more happy to help there (probably I need to have access to this organisation to do it, otherwise, it will cost more time to submit a PR for a wiki).

For now, I removed the `WIP` label, since if we decide to indeed proceed with the fore-mentioned actions, it could even happen afterwards.

**Comment by thodorisbais** [comment]
@keilw I understand (and actually also agree); that was also one of the reasons this PR was marked as WIP, because no matter what is being linked from README to wiki, it will point (in most cases) to a valid wiki page. That said, where should the README link point to? I mean, given your last comment, how do you believe the markdown link should be best changed?

_I think only the EG members have ownership over the wiki page because even after having been added to the organization, I am not able to see any edit-related button._

**Comment by thodorisbais** [comment]
On top of that, even we figure out where to make the README link point to, I still believe we need a `Contribution-Guide` section, just like [indriya](does); otherwise the "contribute" link in README will be useless.

**Comment by Daniel-Dos** [comment]
Hi @thodorisbais ,

about the links, I fixed it now.

**Comment by keilw** [comment]
@Daniel-Dos Thanks, did you fix it here in this PR or outside of it?

**Comment by Daniel-Dos** [comment]
I fixed the link. there is no developer guide, plus I can remove from Indriya and add in api.

when editing the link, I did right on the wiki, I think a PR for the Wiki does not work.

**Comment by Daniel-Dos** [comment]
Hi,

I create the guide -> https://github.com/unitsofmeasurement/unit-api/wiki/Contribution-Guide

**Comment by thodorisbais** [comment]
Great, I just updated the `README` link!

**Pull request merged**
